### ISSUE TITLE
windows 下安装出错。

### ISSUE THREAD

**Issue by newpepsi** [xiewenya/django-aliyun-oss2-storage#29]
ooking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting django-aliyun-oss2-storage
  Downloading https://mirrors.aliyun.com/pypi/packages/cd/59/e22479bac1c97ba9af8b7ce6e3723cd4eea420a8715aa58ac49d631b9604/django-aliyun-oss2-storage-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\newpepsi\AppData\Local\Temp\pycharm-packaging\django-aliyun-oss2-storage\setup.py", line 5, in <module>
        README = readme.read()
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x91 in position 63: illegal multibyte sequence
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\newpepsi\AppData\Local\Temp\pycharm-packaging\django-aliyun-oss2-storage\

**Comment by xianfuxing** [comment]
https://blog.csdn.net/u014633966/article/details/78727034
